### ISSUE TITLE
Exception receiving messages

### ISSUE THREAD

**Issue by engmustafamuhammad** [mgp25/Chat-API-NET#195]
Sending messages working well, but once i receive a message i got this exception

`System.ArgumentNullException was unhandled by user code
  HResult=-2147467261
  Message=Value cannot be null.
Parameter name: source
  ParamName=source
  Source=WhatsAppApi
  StackTrace:
       at WhatsAppApi.WhatsSendBase.processInboundData(Byte[] msgdata, Boolean autoReceipt) in F:\desktop\c\Chat-API-NET-master\WhatsAppApi\Base\WhatsSendBase.cs:line 318
       at WhatsAppApi.WhatsSendBase.pollMessage(Boolean autoReceipt) in F:\desktop\c\Chat-API-NET-master\WhatsAppApi\Base\WhatsSendBase.cs:line 74
       at WhatsAppApi.WhatsSendBase.PollMessages(Boolean autoReceipt) in F:\desktop\c\Chat-API-NET-master\WhatsAppApi\Base\WhatsSendBase.cs:line 60
       at WhatsAppPort.frmForm.ProcessMessages(Object sender, DoWorkEventArgs args) in F:\wp\wp\frmForm.cs:line 82
       at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
       at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
  InnerException: 
`

**Comment by tokzhee** [comment]
I got the same issue. somebody pls help.

**Comment by eaba** [comment]
This could likely be the cause #178

**Comment by tokzhee** [comment]
@eaba:It didn't work for me. Can you receive successfully?
