### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by bilal-fazlani** [mgp25/Chat-API-NET#205]
When calling PollMessages() method, I get the following exception

```
System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=Object reference not set to an instance of an object.
  Source=WhatsAppApi
  StackTrace:
       at WhatsAppApi.WhatsSendBase.processInboundData(Byte[] msgdata, Boolean autoReceipt)
       at WhatsAppApi.WhatsSendBase.pollMessage(Boolean autoReceipt)
       at WhatsAppApi.WhatsSendBase.PollMessages(Boolean autoReceipt)
       at WhatsAppConsole.Program.Main(String[] args) in \\mac\home\documents\visual studio 2015\Projects\WhatsAppPOC\WhatsAppConsole\Program.cs:line 64
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 

```

**Comment by SaschaK** [comment]
I think it's a problem in libaxolotl.ratchet.AliceAxolotlParameters. There is no "ourIdentityKey" (value = null), but I don't know how to fix it
