### ISSUE TITLE
can not compile

### ISSUE THREAD

**Issue by Mahmoud85** [mgp25/Chat-API-NET#87]
I can not compile the project , I use vs 2012 on windows 10 and I receive the following error 

Severity	Code	Description	Project	File	Line
Error		The "Microsoft.Build.Tasks.GenerateResource" task could not be instantiated from "C:\Windows\assembly\GAC_MSIL\Microsoft.Build.Tasks.v3.5\3.5.0.0__b03f5f7f11d50a3a\Microsoft.Build.Tasks.v3.5.dll". 
System.TypeInitializationException: The type initializer for 'Microsoft.Build.Utilities.TaskLoggingHelper' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Collections.Comparer' threw an exception. ---> System.ArgumentException: Customized cultures cannot be passed by LCID, only by name.
   at System.Globalization.CompareInfo.GetCompareInfoWithPrefixedLcid(Int32 cultureKey, Int32 prefix)
   at System.Globalization.CultureInfo.get_CompareInfo()
   at System.Collections.Comparer..ctor(CultureInfo culture)
   at System.Collections.Comparer..cctor()
   --- End of inner exception stack trace ---
   at System.Array.Sort(Array keys, Array items, Int32 index, Int32 length, IComparer comparer)
   at System.Collections.ArrayList.Sort(Int32 index, Int32 count, IComparer comparer)
   at System.Text.RegularExpressions.RegexCharClass.Canonicalize()
   at System.Text.RegularExpressions.RegexCharClass.ToStringClass()
   at System.Text.RegularExpressions.RegexParser.ScanRegex()
   at System.Text.RegularExpressions.RegexParser.Parse(String re, RegexOptions op)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options, Boolean useCache)
   at System.Text.RegularExpressions.Regex..ctor(String pattern, RegexOptions options)
   at Microsoft.Build.Utilities.TaskLoggingHelper..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.Build.Utilities.TaskLoggingHelper..ctor(ITask taskInstance)
   at Microsoft.Build.Utilities.Task..ctor()
   at Microsoft.Build.Utilities.Task..ctor(ResourceManager taskResources, String helpKeywordPrefix)
   at Microsoft.Build.Tasks.TaskExtension..ctor()
   at Microsoft.Build.Tasks.GenerateResource..ctor()	WhatsAppApi

**Comment by mgp25** [comment]
Not API issue
